# Generated by Django 4.2.9 on 2024-05-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0002_movie_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='review_text',
            field=models.TextField(default='llll'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
