# Generated by Django 4.2.9 on 2024-05-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0003_movie_link_movie_review_text_movie_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='review_text',
            field=models.TextField(null=True),
        ),
    ]
