# Generated by Django 4.2.9 on 2024-02-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0003_alter_team_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='img',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
